context:
  version: "0.3.88"

package:
  name: stakpak
  version: ${{ version }}

source:
  url: https://github.com/stakpak/agent/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 7ffae3233a6d97d4bf142392ce747a720b6c94717259ee6527deed91664eeb00

build:
  number: 0
  script:
    env:
      AWS_LC_SYS_CMAKE_BUILDER: ${{ "1" if host_platform == "win-arm64" else "0" }} # force CMake builder for `aws-lc-sys` native C/C++ code on `win-arm64`
      CARGO_PROFILE_RELEASE_LTO: fat
      CARGO_PROFILE_RELEASE_STRIP: symbols
    content:
      - cd cli
      - if: unix
        then:
          - cargo auditable install --path=. --root="$PREFIX" --no-track --locked --bins --features=jemalloc
      - if: win
        then:
          - cargo auditable install --path=. --root="%LIBRARY_PREFIX%" --no-track --locked --bins
      - cargo-bundle-licenses --format=yaml --output=../THIRDPARTY.yml

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-auditable
    - cargo-bundle-licenses
    - cmake
    - pkg-config
    - if: linux
      then: make

tests:
  - script:
      - stakpak help
      - stakpak version
  - package_contents:
      bin:
        - stakpak
      strict: true

about:
  summary: Stakpak – Ship your code, on autopilot.
  description: |
    Stakpak is the open source DevOps agent that helps you with securing, deploying, and maintaining production ready infrastructure and only pings when it needs a human.
    Generate infrastructure code, debug Kubernetes, configure CI/CD, automate deployments, without giving an LLM the keys to production.
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://stakpak.dev
  documentation: https://stakpak.gitbook.io
  repository: https://github.com/stakpak/agent

extra:
  recipe-maintainers:
    - salim-b
