context:
  version: "0.3.71"

package:
  name: stakpak
  version: ${{ version }}

source:
  url: https://github.com/stakpak/agent/archive/refs/tags/v${{ version }}.tar.gz
  sha256: a8a1a66f2c8175bd046d2f56a9f7fca2e5715304abc2d3de2240a66f7b1c9fe4

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - cd cli
      - if: linux
        then:
          # cf. https://github.com/stakpak/agent/blob/main/cli/src/main.rs#L17
          - cargo auditable install --locked --no-track --bins --features jemalloc --root ${{ PREFIX }} --path .
      - if: osx
        then:
          - cargo auditable install --locked --no-track --bins --root ${{ PREFIX }} --path .
      - if: win
        then:
          - cargo auditable install --locked --no-track --bins --root %LIBRARY_PREFIX% --path .
      - cargo-bundle-licenses --format yaml --output ../THIRDPARTY.yml

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-auditable
    - pkg-config
    - if: linux
      then: make

tests:
  - script:
      - stakpak help
      - stakpak version
  - package_contents:
      bin:
        - stakpak
      strict: true

about:
  homepage: https://stakpak.io
  summary: Stakpak – Ship your code, on autopilot.
  description: |
    Stakpak is the open source DevOps agent that helps you with securing, deploying, and maintaining production ready infrastructure and only pings when it needs a human.
    Generate infrastructure code, debug Kubernetes, configure CI/CD, automate deployments, without giving an LLM the keys to production.
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  repository: https://github.com/stakpak/agent

extra:
  recipe-maintainers:
    - salim-b
